### ISSUE TITLE
The House of the Fierce

### ISSUE THREAD

**Issue by AEBus** [pohky/TeleporterPlugin#1]
/tp The House of the Fierce direct
[Teleporter] No valid Aetheryte found for 'The House the Fierce'.

**Comment by CalionSilus** [comment]
Same as above.
[Teleporter] No valid Aetheryte found for 'ハウス（シェア：第1区35番地）'.
[Teleporter] No valid Aetheryte found for 'ハウス (シェア：第1区35番地)'.

**Comment by syntafin** [comment]
Same for New Gridania

**Comment by pohky** [comment]
this should be fixed once the new dalamud version goes live
