### ISSUE TITLE
Feature Request: Chat Command for Teleport Setting

### ISSUE THREAD

**Issue by Ryonez** [pohky/TeleporterPlugin#14]
Basically as the title says, requesting a command to open `Teleporter Config`.

I use QoL Bar to map a lot of various commands, include quick ways to open settings for plugins without needing to open the plugin installer and searching for the plugin.

I'd recommend `/tpc` myself.

**Comment by pohky** [comment]
just `/tp` opens the config already

**Comment by Ryonez** [comment]
So I see. I'd suggest informing uses of that in the discription. The only use of `/tp` mentioned there is for the teleporting itself.
