### ISSUE TITLE
Gil threshold being ignored if teleporting to an Aetheryte in the same zone by clicking on map

### ISSUE THREAD

**Issue by x31s** [pohky/TeleporterPlugin#15]
As the title says, if you teleport to an Aetheryte in the same zone that you are currently in it will always use a ticket, regardless of the cost.

Note: this only seems to happen when clicking on the Aetheryte on the map, if you use the teleport menu it spends the gil just fine instead of using a ticket.

**Comment by pohky** [comment]
i tried to reproduce this but it didn't use tickets if the price was lower than what i had set in the config
could you maybe provide a bit more information, like what your current config looks like and in which zone this happens or if it happens everywhere

**Comment by x31s** [comment]
[Here again with images :)](https://imgur.com/a/k8vL3TO) Happens in every zone.

**Comment by x31s** [comment]
I did a full reinstall today (both game + XIVLauchner on a new drive) and am no longer experiencing this issue. I had previously deleted the plugin config files and reinstalled just the plugin without it changing anything, so there might have been an issue with my game files that caused this to happen. What specifically though I have no idea. Sorry for wasting your time, I consider this issue resolved although I still have no clue what exactly caused this behaviour for me.
