### ISSUE TITLE
[Bug] Teleporting with Gil Limit from the Map is Inconsistent

### ISSUE THREAD

**Issue by cglatot** [pohky/TeleporterPlugin#16]
Hi, I am having a lot of issues that are problematic to get steps to reliably reproduce. When teleporting using the Teleportation list, everything works perfectly fine. Tickets are used or not used appropriately.

However, when teleporting from the map, it's incredibly inconsistent. Sometimes it will work fine, but most times it does not. It will use tickets when it shouldn't, and it will not use tickets when it should.

I first noticed this behaviour when I teleported to a location that SHOULD use a ticket, and then noticed that it was still taking tickets for nearby teleports, when it should not be. I first thought that THIS was the issue, but when I tried to reproduce, it gave me different results each time.

You can see my settings here: 
![image](https://user-images.githubusercontent.com/10439257/143458226-ea47e492-ec0e-4997-850f-385abc6428d6.png)

I have also tried toggling the "Hide Ticket Popup" setting as well and it is equally inconsistent behaviour.

**Comment by pohky** [comment]
this should be fixed now, but it will also likely be removed from the plugin as endwalker adds that feature to the game

**Comment by cglatot** [comment]
> this should be fixed now, but it will also likely be removed from the plugin as endwalker adds that feature to the game

Hahaha yeah I was just thinking that not too long ago as I was reading the patch notes. Thanks for fixing anyway I guess! 😅
