### ISSUE TITLE
Feature Request: Alias TP removal

### ISSUE THREAD

**Issue by DiggityMan420** [pohky/TeleporterPlugin#18]
So I get what alias does but I have to use simple tweaks to get what alias SHOULD do. I use the Simple Tweaks (Command Alias) to make a new command of "/tp go" so i only need to type /go to go to the gold saucer but, the teleport plugin makes the alias it should remove the "tp" part or make a check box to have it optional to remove it or keep it like u have it See my Example [PIC]([img]https://i.ibb.co/sj0HhY2/Screenshot-5.jpg[/img])

In reality I don't even need the alias part is you have "Allow Partial Match" ON u can just make simple tweaks do it for you.
I have Alias in hopes  that you will make it remove the "tp" part so i can just use the alias and remove the simple tweaks part.

**Comment by pohky** [comment]
the alias in Teleporter is an alias for the target location not for the command
it does exactly what it is supposed to do and i will not change that
