### ISSUE TITLE
Alias /tp to /tel

### ISSUE THREAD

**Issue by rdowers** [pohky/TeleporterPlugin#19]
Any chance you can add an alias such that /tel works the same as /tp? My brain says "/tel(eport)" as opposed to "/tp(ort)". I don't know why. :) 

Thank you!

**Comment by nightgrey** [comment]
Tip: You can use Simple Tweaks to add any alias you want.

See https://github.com/Caraxi/SimpleTweaksPlugin. It is in the default Dalamud plugin repository. :)
