### ISSUE TITLE
Feature request: teleport tickets

### ISSUE THREAD

**Issue by Horcrux** [pohky/TeleporterPlugin#3]
Support for GC tickets (e.g. Maelstrom Aetheryte Ticket), Firmament ticket, and Vesper Bay ticket.

Having these as options for aliases would be nice.

Great plugin btw!

**Comment by zenrar** [comment]
plus also the option to add the eternity ring would be awesome.

**Comment by pohky** [comment]
GC Tickets and Eternity Ring are and option in the 2.0.0.0+ version now.
Not adding Firmament and Vesper Bay Tickets for a variety of reasons.
